name: Smoke Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
jobs:
  smoke:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Smoke tests
      run: npx playwright test --grep @smoke
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        API_LOGIN_URL: ${{ secrets.API_LOGIN_URL }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: smoke-report
        path: playwright-report/
        retention-days: 30
